# app/tools/jira_tools.py
import requests
from requests.auth import HTTPBasicAuth
import json
import os
from app.core.config import settings

def create_jira_ticket_logic(summary: str, severity: str) -> str:
    """Core logic to push a P1/P2 ticket to Jira."""
    if not settings.JIRA_API_TOKEN or not settings.JIRA_DOMAIN:
        return "Error: Jira credentials are not fully configured."

    # Jira uses email + API token for auth. 
    # For now, we will pull the email from an env variable.
    jira_email = os.getenv("JIRA_EMAIL", "your-email@example.com")
    
    url = f"https://{settings.JIRA_DOMAIN}.atlassian.net/rest/api/3/issue"
    auth = HTTPBasicAuth(jira_email, settings.JIRA_API_TOKEN)
    headers = {"Accept": "application/json", "Content-Type": "application/json"}

    # ADD THIS PRINT STATEMENT
    print(f"--- DEBUG: Attempting to hit URL: {url} ---")

    # Standard Jira Issue Payload for a Bug/Incident
    payload = json.dumps({
        "fields": {
            "project": {"key": "KAN"}, # Assuming your project key is KAN
            "summary": summary,
            "description": {
                "type": "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": f"Severity: {severity}. Automated incident generated by VoiceOps."}]
                    }
                ]
            },
            "issuetype": {"name": "Task"}
        }
    })

    try:
        response = requests.post(url, data=payload, headers=headers, auth=auth)
        
        if response.status_code == 201:
            issue_key = response.json().get('key')
            return f"CRITICAL SUCCESS: Successfully created Jira ticket {issue_key}. Tell the user this exact ID."
        else:
            return f"CRITICAL FAILURE: The Jira API rejected the request with status {response.status_code}. The error was: {response.text}. YOU MUST TELL THE USER IT FAILED."
            
    except Exception as e:
        return f"CRITICAL FAILURE: System error while connecting to Jira: {str(e)}. YOU MUST TELL THE USER IT FAILED."